
##############################################################
##############################################################
##   Bc. David Vosol (xvosol00)                             ##
##   VUT FIT 2021/2022                                      ##
##   Master's Thesis implementation                         ##
##   config.yaml - Main configuration file                  ##
##   Based on:                                              ##
##############################################################
##############################################################

setup:
  cfg_name:             config.yaml                   # name of this file
  vision:               on                            
  rendering:            on                            # do not set off!
  throttle:             on
  gear_shift:           off                           # not used during exps
  fuel:                 off                           # not used during exps
  noisy_sensors:        off                           # not used during exps
  race_speed:           2                             # <1,..100> - depending on the hardware 1-8 is suitable for CNN training
  normalize:            on                            # Normalize sensor values to interval <0,1>
  reward_function:      2                             # <1,..4>
  track:                eroad                     # Track selection <eroad, e-track-2, forza, e-track-4, e-track-1, g-track-3, michigan, g-track-2> rest in tracks.yaml
  test_track:           eroad                         # Track selection - only for testing during optimization phase (regular learning) 
  determ_actions_test:  off

simulation:
  algorithm:            ppo                           # <ppo, ppo_cnn, ppo_basic..>  where _basic is regular gym environment, without it is TORCS
  ENV_ID:               LunarLanderContinuous-v2      # alternative Gym environment, used before TORCS <BipedalWalker-v3, MountainCarContinuous-v0, RoboschoolHalfCheetah-v1, CarRacing-v0>
  DEVICE:               CPU                           # <CUDA, CPU>

  mode:                 train                                       #<train, eval>                                      # test, valid, experiment, eval
  load_model:           #./checkpoints/nn_cloud_0.05_cont.pth #./checkpoints/e_track2_nn_new_reward-well_trained.pth #./checkpoints/nn_cloud_0.05_cont.pth #./checkpoints/e_track2_nn_new_reward-well_trained.pth #./checkpoints/ppo_04132022-13-34-40.pth #./checkpoints/cnn_pickle.pth                #path of model to retrain (pretrained model)
  race_config_path:     ./raceconfigs/default.xml                   #race config for the Torcs
  # optimization:         one_head                                    #<one_head, two_head>   actor and critic shares the same neural net or not    NOT USED
  architecture:         nn                            # <cnn,nn, nn_cnn>
  img_num:              1                             # if architecture 'cnn' -> how many pics it uses <1,2>
  img_type:             reg                           # <reg,diff>  #regular image or image difference, in combination with above option img_num
  cnn_type:             4                             # <1-7> Type of CNN network for image input            
  tracks_config:        ./tracks.yaml                 # config file with tracks info
  record_samples:       off                           # whether to record samples [image,sensors] for explicit CNN learning - to replace real sensor values
  
  comm_delay:           off                           # simulation of network delay     #NOT USED
  comm_failure:         off                             # simulation of packet loss
  sensor_noise:         off                             # simulation of sensor fail/noise

  comm_prob:            0.05                           # 0.05 default, <0,1> used only when comm_failure ON
  noise_prob:           0.05                           # 0.05 default, <0,1> used only when sensor_noise ON


  #If trained CNN model from recorded samples (IMG->sensors) <angle,track> (20 values)
  cnn_to_sensors:       off                           #architecture=cnn, img_type=reg, img_num=1
  cnn_to_sensors_path:  #./checkpoints/model_cnn_to_sensors-TRAINED_CNN_slow_overfitted.pth #model_cnn_to_sensors-TRAINED_CNN_slow_overfitted.pth #model_cnn_to_sensors-TRAINED_CNN.pth

# torcs:
#   race_mode:            practice                    # <practice, race,..>    race type                                                     NOT USED
#   opponents:            0                           # <0,..16>                                                                             NOT USED
#   capture:              off                         # capture video output or not                                                          NOT USED

ppo:
  #PPO Hyperparameters
  LEARN_RATE:           0.0001                        # !!float 1e-4
  GAMMA:                0.99
  GAE_LAMBDA:           0.95
  PPO_EPSILON:          0.2
  CRITIC_DISCOUNT:      0.5
  ENTROPY_BETA:         0.001
  MINI_BATCH_SIZE:      32                            # batch size has to be simular or smaller that PPO_STEPS (division by zero!)
  PPO_EPOCHS:           20 #40 #20                    # PPO updates of parameters (from experience)

  #Optimization Hyperparameters
  NUM_ENVS:             1   #4 #6                     # number of environments, NUM_ENV > 1 means parallelization
  STD_DEV:              0.1
  NUM_OF_LAYERS:        2                             # <1,2> number of hidden layers
  HIDDEN_SIZE_AC:       512                           # <64,128,256,512,..> number of neurons in hidden layer in AC network
  HIDDEN_SIZE_CNN:      512                           # hidden linear layer in CNN network
  OUT_CNN:              120                           # out img features for AC network
  PPO_STEPS:            1600 #768                     # steps in environment everytime done - DONE (masks out) #at best, it should be multiple of MINI_BATCH_SIZE
  TEST_EPOCHS:          5                             # how often put agent into the test for results..
  SAVE_EPOCHS:          20                            # currently it has to be divisible by TEST_EPOCHS bcs it is inside that IF
  NUM_TESTS:            10   #10                      # how many tests will be done during EVAL phase in test_env_torcs with loaded_model
  EARLY_STOP:           on                            # if ON, then simu ends by reaching TARGET_REWARD or TARGET_STEP, else by TOTAL_EPOCHS
  TARGET_REWARD:        250000                        # when earlyStop - end the training after TARGET_REWARD reached by the agent
  TARGET_STEP:          650000                        # when earlyStop - end the training after TARGET_STEP simulation steps
  TOTAL_EPOCHS:         3000
  IMG_MODE:             rgb                           #gr1 - grayscale 1d (for linear NN), gr (64x64), rgb(64x64x3) NOT USED
  TEST_STEPS:           1600 #2000                    #max length of a testing episode (if not done)

sensors:
  focus:                off      #USED
  speedX:               on       #USED DO NOT TURN OFF!
  speedY:               off      #USED
  speedZ:               off      #USED
  angle:                off      #USED
  damage:               on       #USED for internal statistics only, DO NOT TURN OFF! 
  opponents:            off
  rpm:                  off      #USED
  track:                on       #USED   #when CNN_TO_SENSORS we have to TURN IT OFF
  trackPos:             off      #USED
  wheelSpinVel:         off      #USED
  lap:                  off
  distRaced:            on       #USED for internal statistics only, DO NOT TURN OFF! 
  img:                  off      #do not turn on, camera output is triggered by choosing the network arch: <nn, cnn>
  gear:                 off
  z:                    off
  curLapTime:           off
  fuel:                 off
  lastLapTime:          off
  totalDistFromStart:   off
  racePos:              off
  distFromStart:        off


PPO2:



PPO3:
  HIDDEN_SIZE:        64    #number of neurons within hidden layer
  HIDDEN_NUM:         2     #number of hidden layers
  GAMMA:              0.99
  SEED:               0
  NUM_CPU:            1
  STEPS:              300
  EPOCHS:             2000

  CLIP_RATIO:         0.2
  PI_LEARN_RATE:      0.0003
  V_LEARN_RATE:       0.001
  PI_TRAIN_ITERS:     40
  V_TRAIN_ITERS:      40
  GAE_LAMBDA:         0.97
  EPISODE_MAX_STEPS:  500
  TARGET_KL:          0.01    #0.01 bylo do ted..
  SAVE_MODEL_FREQ:    10
